Fix Linux/GCC build after the previous commit.
ip6.h now needs netdissect.h, fix includes order where required to fix:

./ip6.h:181:2: error: unknown type name ‘nd_uint8_t’
  nd_uint8_t  ip6r0_nxt;  /* next header */
  ^
./ip6.h:182:2: error: unknown type name ‘nd_uint8_t’
  nd_uint8_t  ip6r0_len;  /* length in units of 8 octets */
  ^
./ip6.h:183:2: error: unknown type name ‘nd_uint8_t’
  nd_uint8_t  ip6r0_type;  /* always zero */
  ^
./ip6.h:184:2: error: unknown type name ‘nd_uint8_t’
  nd_uint8_t  ip6r0_segleft; /* segments left */
  ^
./ip6.h:185:2: error: unknown type name ‘nd_uint32_t’
  nd_uint32_t ip6r0_reserved; /* reserved field */
  ^