fix compilation on FreeBSD 10.1
Commit 05d7191 fixed detection of Capsicum availability and the
Capsicum-specific code in tcpdump made it into the compilation process
on respective FreeBSD systems. However, it would fail to compile at
least on FreeBSD 10.1-RELEASE as quoted below. This commit fixes it.

In file included from ./tcpdump.c:89:
/usr/include/net/bpf.h:65:8: error: redefinition of 'bpf_program'
struct bpf_program {
       ^
../libpcap/pcap/bpf.h:106:8: note: previous definition is here
struct bpf_program {
       ^
In file included from ./tcpdump.c:89:
/usr/include/net/bpf.h:1206:8: error: redefinition of 'bpf_insn'
struct bpf_insn {
       ^
../libpcap/pcap/bpf.h:1466:8: note: previous definition is here
struct bpf_insn {
       ^
2 errors generated.