ENC: Lose an unused variable after commit 1de5051.
NetBSD 9.2/AArch64
clang version 13.0.0

./print-enc.c:103:8: error: variable 'caplen' set but not used
 [-Werror,-Wunused-but-set-variable]

(cherry picked from commit e1ee2a34a9e8dc5bdc1b69aae8c77f0a5b1ae23c)