Remove init_crc10_table() and the entourage.
As Guy Harris points out in bug report GH #1022, the function has been a
busy no-op since commit e6c39e6 in 2010.  While at it, fixup the Python
code to work on Python 3:

    for i in range(len(crc_table)/8):
TypeError: 'float' object cannot be interpreted as an integer

(cherry picked from commit 94f232c1ab0143c6da9fc00732b6b241b8abdf4c)