Capsicum support: Fix a 'not defined' macro error
The error was:
In file included from ./tcpdump.c:158:
./interface.h:62:32: error: "HAVE_CAPSICUM" is not defined, evaluates
to 0 [-Werror=undef]
   62 |     (defined(HAVE_BPF_DUMP) && HAVE_CAPSICUM && !defined(bpf_dump))
      |                                ^~~~~~~~~~~~~

(cherry picked from commit bfc96b04831641376636337406aae7fe0fe65081)