Treat SA_RESTART as optional.
QNX 8.0 implements sigaction(), but not SA_RESTART.  This is not ideal,
but tolerable for simple use cases.

tcpdump.c:3030:32: error: 'SA_RESTART' undeclared (first use in this
  function); did you mean 'ERESTART'?

(cherry picked from commit cd4ed7f36576a8fe47872f4738f1b86202365810)